### ISSUE TITLE
Se puede colaborar?

### ISSUE THREAD

**Issue by arielhernandezcl** [sysarmy/2024.nerdear.la#2]
Hola, encontre algunos detalles en el html del sitio con respecto al seo y la accesibilidad 

![image](https://github.com/sysarmy/2024.nerdear.la/assets/63879018/ecec32b4-45ff-42b8-971b-a91528ec2a5c)

Puedo colaborar haciendo una pr con las mejoras?

Un abrazo

**Comment by arieljolo** [comment]
Claro ! Muchas gracias!


<https://sysar.my/linktrees>

*Ariel Jolo*

Founder / BDFL
+54 911 3269 5533

Book a meeting! <https://zcal.co/nerdearla/discovery>

[image: Twitter] <https://sysar.my/twitters> [image: LinkedIn]
<https://sysar.my/linkedins> [image: Spotify]
<https://sysar.my/spotifys> [image:
Instagram] <https://sysar.my/instagrams> [image: YouTube]
<https://sysar.my/youtubes>
